# Generated by Django 4.0.6 on 2022-07-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=20)),
                ('last_Name', models.CharField(max_length=20)),
                ('address_Name', models.TextField()),
                ('email_Address', models.EmailField(max_length=254)),
                ('phone_Number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
